# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='humidity',
        ),
    ]
